# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0b68a85b-8a1e-48f8-b5f6-0b78b95e3975";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0b68a85b-8a1e-48f8-b5f6-0b78b95e3975".device = "/dev/disk/by-uuid/0b68a85b-8a1e-48f8-b5f6-0b78b95e3975";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/78CF-24E1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
